### ISSUE TITLE
Embed Youtube videos

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#1]
I think its a great idea to embed youtube videos and other coming up contents, blogs, articles, community, etc on a new page.
So that there is more to see when a user gets to our website.

**Comment by KeenWarrior** [comment]
@Abhishek-kumar09 Hey. We were inactive for some time. Your idea is good and we can certainly use it.

We are adding up the link to Figma in the readme.

**Comment by Abhishek-kumar09** [comment]
As I heard about, `code for cause` website is going to be launched... Is this code is the codebase for that new website.

**Comment by KeenWarrior** [comment]
@Abhishek-kumar09 Yes. This is the codebase for the website.

**Comment by KeenWarrior** [comment]
[Figma PDF](https://github.com/codeforcauseorg/codeforcause.org/files/4820322/MacBook.Pro.-.53.pdf)

Here is the draft version of Figma structure. The complete version will be available soon. 

Contributions are welcome.

**Comment by Abhishek-kumar09** [comment]
I think it will be a good idea to upload all the logos, assets, png, etc in the assets of development branch.

**Comment by KeenWarrior** [comment]
@Abhishek-kumar09 I have added 2 issues. You can choose which one you like and corresponding to that we can help you proceed.

**Comment by KeenWarrior** [comment]
This is not fitting in the current plan of home page. Closing this issue for right now.
