### ISSUE TITLE
Login button overlapping with logo in mobile view

### ISSUE THREAD

**Issue by ujjwal404** [codeforcauseorg/codeforcause.org#101]
![WhatsApp Image 2020-09-28 at 7 29 00 AM](https://user-images.githubusercontent.com/63122405/94383033-7ebf0900-015c-11eb-9fe7-1f311696be1b.jpeg)

**Comment by Abhishek-kumar09** [comment]
A big thank to you for opening this issue, It was gone unnoticed.

**Comment by Navya-Andra** [comment]
I want to work on this issue. Please assign it to me.

**Comment by Abhishek-kumar09** [comment]
Really sorry, I had just linked a PR fixing it. But I have another issue that you can solve. I will ping you there once I open it.
