### ISSUE TITLE
Distortion in check details button on smaller devices.

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#103]
Distortion in check detail button on smaller/mobile screens:
[see image](https://user-images.githubusercontent.com/48255244/94452010-b36aa900-01cc-11eb-8323-1ab5c79d4207.png)

**Steps to reproduce:**
1. Visit codeforcause homepage on mobile device
2. scroll down to course section
3. Check details button is cropped from bottom.

**Comment by Abhishek-kumar09** [comment]
@Navya-Andra Do you want to look at it.

**Comment by Navya-Andra** [comment]
Thank you for considering. I will work on it. please assign.

**Comment by Abhishek-kumar09** [comment]
@Navya-Andra Here is the code: https://github.com/codeforcauseorg/codeforcause.org/blob/development/src/views/pages/common/CourseCard.js#L198-L219

**Comment by Navya-Andra** [comment]
> @Navya-Andra Here is the code: https://github.com/codeforcauseorg/codeforcause.org/blob/development/src/views/pages/common/CourseCard.js#L198-L219

this link is throwing 404 error

**Comment by Abhishek-kumar09** [comment]
because it has been migrated.
https://github.com/codeforcauseorg/codeforcause.org/blob/development/src/components/Course/CourseCardTemplate1.js

**Comment by Abhishek-kumar09** [comment]
Contributions are welcome.

**Comment by Abhishek-kumar09** [comment]
Contributions are welcome, she cannot complete this PR due to her exams and technical difficulties from her end.

**Comment by deekshithpranav** [comment]
Hello, @Abhishek-kumar09 I am a beginner and I would like to work on this, can you help me get started?

**Comment by Abhishek-kumar09** [comment]
Yes, it is solved in some random PR.
Thanks for showing your interest.
I would suggest you some other beginner friendly issue.

**Comment by deekshithpranav** [comment]
> Yes, it is solved in some random PR.
> Thanks for showing your interest.
> I would suggest you some other beginner friendly issue.

Thanks. That would be great ☺️, let me know if there are any beginner-friendly issues.
