### ISSUE TITLE
Overlapping of home page cards 

### ISSUE THREAD

**Issue by madhhuurrii** [codeforcauseorg/codeforcause.org#104]
## Description 
The Code for cause card is overlapping with the mentors card in home page in mobile view.
## Steps to reproduce
1. Click on live website 
2. Scroll through homepage
3. See the error
## Screenshot 
![20200929_103541](https://user-images.githubusercontent.com/64744084/94514790-bbaffc00-023f-11eb-81ee-5589cd777038.jpg)

## Mobile
OS: Android 10
Model: Samsung Galaxy M30s
Browser : Samsung Internet

**Comment by Abhishek-kumar09** [comment]
@madhhuurrii Thank you very much for opening this issue: We are fixing it in https://github.com/codeforcauseorg/codeforcause.org/pull/102

**Comment by Abhishek-kumar09** [comment]
Fixed is merged.
