### ISSUE TITLE
[docs] Broken link in README

### ISSUE THREAD

**Issue by pandafy** [codeforcauseorg/codeforcause.org#108]
I found this link to be broken in REAME. Moreover, I think that this should be https://sandbox.codeforcause.org instead, but I am not sure. 

https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/README.md#L8

**Comment by KeenWarrior** [comment]
Yes. we have removed auth from authbox for firebase.

**Comment by pandafy** [comment]
@KeenWarrior should this be entirely removed or changed to https://sandbox.codeforcause.org? Doing later, doesn't makes much sense since this link is mentioned in the section below.
