### ISSUE TITLE
Update font family

### ISSUE THREAD

**Issue by KeenWarrior** [codeforcauseorg/codeforcause.org#11]
Update font family for the website to Montserrat

you can find the detail of font at https://fonts.google.com/specimen/Montserrat

**Comment by icodechiranjib** [comment]
I'll work on this.

**Comment by Abhishek-kumar09** [comment]
@icodechiranjib Are you working on it?

**Comment by KeenWarrior** [comment]
@Abhishek-kumar09 You can proceed with it if you like to.

**Comment by Roshan13046** [comment]
Hi, I would like to work on this issue, can you please, suggest me ways to get started?

**Comment by KeenWarrior** [comment]
@Roshan13046 This one is taken. Can you tell me what is your preference in issues? We are generating more of them. I can suggest some to you based on your interest.

**Comment by Roshan13046** [comment]
Please, Suggest issues related to HTML, CSS, js, react.
I would like to work on them.
