### ISSUE TITLE
Scrollbar looks dull in the website 

### ISSUE THREAD

**Issue by ArunTeltia** [codeforcauseorg/codeforcause.org#119]
Can I customize the scroll bar in the website so that it will not look dull like present
I will send the screenshot before the pull request
Can i work on this ? 
Edit : I think this will look great with the website theme
![scroll](https://user-images.githubusercontent.com/43555219/95021725-5705fe80-0690-11eb-9287-3c5464a8eb8b.JPG)

**Comment by Abhishek-kumar09** [comment]
@ArunTeltia Go on, we will be looking for your PR.

**Comment by ArunTeltia** [comment]
check this out i think this is looking great with the current theme of the website @Abhishek-kumar09 
![scc](https://user-images.githubusercontent.com/43555219/95028117-99910080-06bb-11eb-8743-30762a6010e8.JPG)

**Comment by Abhishek-kumar09** [comment]
Please make a PR against the development branch, and we will discuss further there. To me it is looking good.

**Comment by Abhishek-kumar09** [comment]
Closed
