### ISSUE TITLE
Console shows firebase auth token just after logging in

### ISSUE THREAD

**Issue by ujjwal404** [codeforcauseorg/codeforcause.org#123]
![Screenshot 2020-10-05 at 5 19 43 PM](https://user-images.githubusercontent.com/63122405/95077216-bae00400-0730-11eb-980b-81a3a5eaed8b.png)

**Comment by KeenWarrior** [comment]
A simple console log needs to be removed from authservice.js file. would you like to work on it?

**Comment by ujjwal404** [comment]
@KeenWarrior Yes I've fixed it in PR #124 and it has been approved too.

**Comment by Abhishek-kumar09** [comment]
Fixed in #124
