### ISSUE TITLE
Put a placeholder until data is loaded from axios

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#137]
https://github.com/codeforcauseorg/codeforcause.org/blob/d22cc28cbeedef8557d08a8b063a9910fbd49b26/src/views/pages/HomeView/Events.js#L119-L121
Currently null is returned untill the data is fully loaded, we don't want it. Else there should be some placeholder there that displayed untill the data is fully loaded.

You can see this with landing on the homepage, and realising that the `*Events Section* is loaded after some time disturbing the scroll position.

**Comment by amity-ak97** [comment]
Hey, I would love to work on this. Assign me and please help me understand this issue in detail.

**Comment by Abhishek-kumar09** [comment]
Go on codeforcause.org, on the topbar click on events.
You will feel that nothing is rendered untill the data is loaded, We want to have some placeholder or loader there so as to expect some data yet to come. Currently, the things are rendered spontaneously disturbing the scroll position which may not be expected by the user.
The changes will likely to be done at the line linked in the PR description.

**Comment by amity-ak97** [comment]
Hey @Abhishek-kumar09, I am new here and am struggling to set up the local development environment for this project. Any suggestions for me? Thanks.

**Comment by Abhishek-kumar09** [comment]
No problem @amity-ak97, just tell me where you need a help.
What are your error logs and where are you failing?

**Comment by amity-ak97** [comment]
@Abhishek-kumar09 
There are no errors actually, I need the help to launch the website locally.
