### ISSUE TITLE
Create Hire-With-Us page

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#199]
We code for cause are commited to provide opportunities to everyone we know, for maximizing the reach to job providers an Hire-with-us page is strongly needed.
We can make this by breaking things into components:
Download full pdf prototype: 

[Hire With us-min.zip](https://github.com/codeforcauseorg/codeforcause.org/files/5862915/Hire.With.us-min.zip)

There are smaller issues linked to it, we should write the code for seperate components as component issues are linked with it.

You should create page in https://github.com/codeforcauseorg/codeforcause.org/tree/development/src/views/pages by making its seperate folder. 

Ping with tagging any of the project maintainer for any small or big help.

**Comment by mdPial** [comment]
Hello, I would like to work on that issue 😃

**Comment by Abhishek-kumar09** [comment]
@mdPial, sure! you can start with making any of the component in the referenced issues, 
We use material-ui for the project, you can definately look onto it.
For any resources, images etc, reach out to me. I am more than happy to help.

**Comment by Abhishek-kumar09** [comment]
You can comment on any of the referenced issue for the components you want to make.

**Comment by mdPial** [comment]
Sure. Your friendly attitude has reduced my nervousness. Thank you.

**Comment by Abhishek-kumar09** [comment]
You are lovely too!

**Comment by PranxXxD** [comment]
Hey!, I would like to work with the issue, help me so that I can start with it

**Comment by Abhishek-kumar09** [comment]
@PranxXxD you can start with component2 or component 3. Just comment on the respective component you want  to choose. 
Infact you can try making any of the component from https://github.com/codeforcauseorg/codeforcause.org/files/5862915/Hire.With.us-min.zip

Just comment or create an respective issue for the component you are making. Any other help from react or anything, you can contact me with tagging me like this: @Abhishek-kumar09

**Comment by PranxXxD** [comment]
@Abhishek-kumar09 I would like to get started with the #202

**Comment by adarsh500** [comment]
Hey, @Abhishek-kumar09 this is my first time here. I would like to work on this. If there is anything I can do to help then please let me know.

**Comment by Abhishek-kumar09** [comment]
Hi @adarsh500 This issue's children are closed, maybe there is need of some nits for the page, it is open for that. If you find any issue with hireWithUs page you can make a PR.
If you want to work on some newer issues This is the list of issues that we need help with https://github.com/codeforcauseorg/causefolio/issues

If you want I can create some newer issues from design component or share the designs with you.

**Comment by Arkashish** [comment]
Hi @Abhishek-kumar09 . I'm extremely new to open source and I would like to contribute can you please help me getting started.

**Comment by Abhishek-kumar09** [comment]
Hi @Arkashish thanks for stopping by.
This issue is closed for now, since the children issues are already solved.
If you want there are several other projects that  need your help like click-short, causefolio, edu-server.
You can help there, try to pick an issue or setup the development environment and find issues for yourself to work on.
