### ISSUE TITLE
Create Hire-With-Us Hero component

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#200]
Create hire-with us Hero component
Here is the hero component:
![image](https://user-images.githubusercontent.com/48255244/105638564-352bc400-5e99-11eb-835b-1ced73184db1.png)

Here is the full prototype: https://github.com/codeforcauseorg/codeforcause.org/issues/199

**Comment by Abhishek-kumar09** [comment]
Yes, I could provide you the background image that will help you for now.

**Comment by Abhishek-kumar09** [comment]
[Rectangle 1047.zip](https://github.com/codeforcauseorg/codeforcause.org/files/5889139/Rectangle.1047.zip)

**Comment by Abhishek-kumar09** [comment]
You can reach out for any other help

**Comment by mdPial** [comment]
Sure. I will 😃️

**Comment by mdPial** [comment]
Will the image location of Rectangle 1047.png like this?
.
├── public
	├── static
		├── images
			├── hire with us
				├── Rectangle 1047.png

**Comment by Abhishek-kumar09** [comment]
yes

**Comment by mdPial** [comment]
Do I need to use **HeroWithLogo** component to design this component?. I am facing issue to making the component look like this because of the background image by using that component.

**Comment by Abhishek-kumar09** [comment]
You could use that or create your own component in different file with doing some changes to `heroWithLogo` component.

**Comment by mdPial** [comment]
Okay.

**Comment by mdPial** [comment]
![image](https://user-images.githubusercontent.com/43095489/106426272-85091d00-648f-11eb-8bcc-6413c13fd953.png)

Are everything alright?

**Comment by Abhishek-kumar09** [comment]
@mdPial  We will discuss the rest in the PR. Please create a PR against development branch after running `npm run format`

**Comment by mdPial** [comment]
@Abhishek-kumar09  Please check my PR. I have made a pull request.

**Comment by Abhishek-kumar09** [comment]
Merged in #206
