### ISSUE TITLE
Create Hire-with-us component-2

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#201]
Here is the component design
![image](https://user-images.githubusercontent.com/48255244/105638762-94d69f00-5e9a-11eb-9433-44f3aeb99177.png)
Here is the full prototype: #199

**Comment by atharmohammad** [comment]
Hey, I would Like to work on this issue

**Comment by Abhishek-kumar09** [comment]
Sure, here is the page folder for hireWithUs: https://github.com/codeforcauseorg/codeforcause.org/tree/development/src/views/pages/HireWithUsView

Here is the css for that box: 
```
width: 239px;
height: 170px;
background: rgba(255, 255, 255, 0.1);
box-shadow: 0px 0px 14px rgba(0, 0, 0, 0.1), inset 0px 0px 18px #BAAEAE;
border-radius: 121.5px 20px 121px 121.5px;
```
[Rectangle 957.zip](https://github.com/codeforcauseorg/codeforcause.org/files/5936476/Rectangle.957.zip)

**Comment by atharmohammad** [comment]
@Abhishek-kumar09  Thanks mate, I am on it, can you provide me with those ribbons and book icons or should I crop it from the above image,I tried to find them on google but i can't find them similar to these

**Comment by Abhishek-kumar09** [comment]
I would provide you those, I just cant find it now. You can replace it with any svg for now. Will try to provide asap.

**Comment by atharmohammad** [comment]
![update](https://user-images.githubusercontent.com/56029409/107119614-da3d9800-68ae-11eb-8a76-51d3e6105d10.PNG)

1. Can you tell me the Backgroud Color of Boxes  and the component .
2. Also Tell me if there are changes required 
Thanks! 👍

**Comment by Abhishek-kumar09** [comment]
Create a PR and we will discuss further.
