### ISSUE TITLE
Create Hire-With-Us component 3

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#202]
Here is the component design: 
![image](https://user-images.githubusercontent.com/48255244/105639096-4e823f80-5e9c-11eb-8dcc-029c56648eb9.png)
here is the full prototype #199

**Comment by Abhishek-kumar09** [comment]
@PranxXxD
For the help those rectangles could be made something like: 
```
width: 450.78px;
height: 76.8px;
background: #EBEBEB;
border-radius: 121.5px 0px 121px 121.5px;
transform: matrix(-0.99, 0.16, -0.11, -0.99, 0, 0);
```

Here is the png image: 
[im.zip](https://github.com/codeforcauseorg/codeforcause.org/files/5897661/im.zip)

**Comment by PranxXxD** [comment]
@Abhishek-kumar09 can please more specify with the issue!

**Comment by PranxXxD** [comment]
@Abhishek-kumar09 can you please more specify with the issue!

**Comment by Abhishek-kumar09** [comment]
You have to make a component something like seen in the PR description, You have to put your component in the `src/components` folder.
You can add a route to your component in `src/routes.js`

**Comment by atharmohammad** [comment]
@Abhishek-kumar09  Hey If no one is working on this I would like to take this issue

**Comment by Abhishek-kumar09** [comment]
@atharmohammad 
Go on.
