### ISSUE TITLE
"node_modules/agent-base/dist/src/index not found" error

### ISSUE THREAD

**Issue by mdPial** [codeforcauseorg/codeforcause.org#205]
I don't know I am the only one is getting this error or not. I think we could exclude the node_modules.
![image](https://user-images.githubusercontent.com/43095489/106235685-5e47ae00-6225-11eb-8b78-effd432e2907.png)

**Comment by Abhishek-kumar09** [comment]
@mdPial which command got you there with these errors?

**Comment by mdPial** [comment]
after running `npm install` . I have tried couple of time `npm install` that time to see, was there anything missing. But it showed that error everytime. May be it is a problem of **npm**. After deleting the local repository I again cloned into local machine and tried `npm install`  and that time error didn't occurred.

**Comment by Abhishek-kumar09** [comment]
coool

**Comment by Abhishek-kumar09** [comment]
I guess issue is solved. Re-open if needed.
