### ISSUE TITLE
Create Hire-with-us component 4

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#223]
The component to make: 
![image](https://user-images.githubusercontent.com/48255244/107810008-fb602600-6d91-11eb-8364-273c0dc88382.png)

Please let me know about the any aditional file you want, and react out for any help with the issue.

**Comment by niteshsinha17** [comment]
Hii, i would like to work on this. ☺ 
I will reach out to you for any requirements.

**Comment by PrashubhAtri** [comment]
Hey at what url would you like this page to be??
Also, any specific styling in mind or its upto us??

**Comment by niteshsinha17** [comment]
I think it will be used in a different page as a component. Am I right? @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
It is a subset of https://github.com/codeforcauseorg/codeforcause.org/issues/199

The pages and routes are already created you just have to make a component.

The route is `/hirewithus`

The page folder is https://github.com/codeforcauseorg/codeforcause.org/tree/development/src/views/pages/HireWithUsView

Just you have to make this component and import it here: https://github.com/codeforcauseorg/codeforcause.org/blob/development/src/views/pages/HireWithUsView/index.js

I will be sharing you the required files and images

**Comment by Abhishek-kumar09** [comment]
To make those smaller shapes
```
position: absolute;
width: 46.66px;
height: 73.68px;

background: rgba(38, 46, 255, 0.1);
box-shadow: inset 0px 0px 50px rgba(0, 0, 0, 0.25);
border-radius: 300px 14px 760px 300px;
transform: rotate(-88.56deg);
```
Required files:
[hr4.zip](https://github.com/codeforcauseorg/codeforcause.org/files/5976026/hr4.zip)

**Comment by Abhishek-kumar09** [comment]
make sure you are working with latest development branch.

**Comment by PrashubhAtri** [comment]
The component to be imported is to be added at the very top ??

**Comment by Abhishek-kumar09** [comment]
[Hire With us-min.pdf](https://github.com/codeforcauseorg/codeforcause.org/files/5976168/Hire.With.us-min.pdf)

First of all, let me know who is working on this issue and who like to take up @PrashubhAtri @niteshsinha17 so as to avoid confusion and redundant PR.

**Comment by PrashubhAtri** [comment]
I am willing to work and have started creating the component

**Comment by niteshsinha17** [comment]
I have started to work on it since I have commented. It will great if @Abhishek-kumar09 can help in this situation. Thank you.

**Comment by Abhishek-kumar09** [comment]
I don't know but since @niteshsinha17 has commented earlier on this issue with quote: `"Hii, i would like to work on this."`, this particular issue goes to him.

I would like to ask for apology from @PrashubhAtri.

But no worries I will be assigning and giving you a brand new issue to work on, chill.

**Comment by PrashubhAtri** [comment]
no problem I understand. Looking forward to some new issues to work on.

**Comment by niteshsinha17** [comment]
@Abhishek-kumar09 Hii, I have created the required component but I want to know what to do with image part in phone view. Should I hide it or show it at the bottom of the text?

**Comment by Abhishek-kumar09** [comment]
In the phone view, the image should some up followed by the text and then button

**Comment by niteshsinha17** [comment]
> To make those smaller shapes

I think we can use those shapes as image and position them as their position. If you agree then I can create it, else I will be styling them using css.

**Comment by Abhishek-kumar09** [comment]
Whatever you like, do you need the images


> > To make those smaller shapes
> 
> I think we can use those shapes as image and position them as their position. If you agree then I can create it, else I will be styling them using css.

**Comment by niteshsinha17** [comment]
If you can send then please send. Otherwise I will design it.

**Comment by Abhishek-kumar09** [comment]
[Rectangle 103.zip](https://github.com/codeforcauseorg/codeforcause.org/files/5982526/Rectangle.103.zip)

Just rotate and resize these and things will work fine.

**Comment by niteshsinha17** [comment]
Thanks

**Comment by niteshsinha17** [comment]
Hii, `npm run format` is formatting every file. It will show changes in my PR. what should I do?

**Comment by niteshsinha17** [comment]
I have checked it again. No file is actually changed accept few ones but why they are showing changed by the git? I think it my not reflect in my PR.

**Comment by Abhishek-kumar09** [comment]
npm run foramt formats your code that should align to pre-written coding style configuration. It is required to run npm run format after doing cchanges so that code comes in a good written format. You can add those changes to git and commit it in the PR.

**Comment by Abhishek-kumar09** [comment]
@niteshsinha17 Create a PR and we will discuss further steps there.

**Comment by niteshsinha17** [comment]
I have created PR for it.
