### ISSUE TITLE
Remove errors from developer console window on coursepage

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#232]
We need to get rid of all the errors from the developer console window from the coursepage.
Most of the errors are already removed in https://github.com/codeforcauseorg/codeforcause.org/pull/197

**Comment by Abhishek-kumar09** [comment]
@PrashubhAtri Do you want take this?

**Comment by PrashubhAtri** [comment]
Yes I will get started with it

**Comment by PrashubhAtri** [comment]
@Abhishek-kumar09  
![image](https://user-images.githubusercontent.com/53150484/108752283-45eb5a80-7569-11eb-99ca-817f17e4e613.png)
What is this tag for ?

**Comment by PrashubhAtri** [comment]
I am unable to find errors on the course page can you please share the errrors screenshot

**Comment by Abhishek-kumar09** [comment]
@PrashubhAtri click on any course, and then you get course page. 
like this page: https://sandbox.codeforcause.org/courses/ds-algo-with-java

**Comment by PrashubhAtri** [comment]
Ok

**Comment by PrashubhAtri** [comment]
Also I have to make contributions against which branch ??

**Comment by PrashubhAtri** [comment]
I have created a PR please check @Abhishek-kumar09
