### ISSUE TITLE
Add start Learning Today [View]

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#26]
![image](https://user-images.githubusercontent.com/48255244/86475694-c6ebac80-bd62-11ea-934d-c56951ba3042.png)

Do we have that play button svg already available?

**Comment by GangaChatrvedi** [comment]
Yes we have. Attaching it here : 
[playBtn.zip](https://github.com/codeforcauseorg/codeforcause.org/files/4873028/playBtn.zip)

I've attached 2 images. Use what you feel suitable.

And also mobile view for this section should look like
[mobile_view.zip](https://github.com/codeforcauseorg/codeforcause.org/files/4872985/mobile_view.zip)

**Comment by Abhishek-kumar09** [comment]
I am working on it.

**Comment by GangaChatrvedi** [comment]
Open https://www.youtube.com/codeforcause in new tab on clicking play button.

**Comment by Abhishek-kumar09** [comment]
> Open [youtube.com/codeforcause](https://www.youtube.com/codeforcause) in new tab on clicking play button.

Oh! I missed your comment, currently the `Link` is heading to `homepage`. I will make changes tomorrow cause I have switched off my laptop :)

**Comment by GangaChatrvedi** [comment]
@Abhishek-kumar09 Take a look at [this](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). It will help you create better PR description.

**Comment by GangaChatrvedi** [comment]
Closed with #27

**Comment by Abhishek-kumar09** [comment]
Thanks @GangaChatrvedi , That was helpful.
