### ISSUE TITLE
Alignment of a part of a footer.

### ISSUE THREAD

**Issue by ritik-vashist** [codeforcauseorg/codeforcause.org#264]
The footer section (the copyright section) appeared to be left-aligned, but I think making it center-aligned will look symmetrical. And I can work on this issue. @Abhishek-kumar09 If this issue/change helpful I can make it.

**Comment by gauravk268** [comment]
I think this issue is resolved and PR has been opened for this in [issue #234](https://github.com/codeforcauseorg/codeforcause.org/issues/234). @Abhishek-kumar09 this issue can be closed.
