### ISSUE TITLE
Redesigning navigation drawer (mobile view)

### ISSUE THREAD

**Issue by mayankchaudhary19** [codeforcauseorg/codeforcause.org#272]
Navigation drawer for mobile view:
<table>
<tr>
<td> 
Old -

![nav-drawer-old](https://user-images.githubusercontent.com/43718753/119226386-6bffa700-bb26-11eb-950f-2cbe6475fab6.png)
</td>
<td>
New-

![nav-drawer-new](https://user-images.githubusercontent.com/43718753/119226383-6ace7a00-bb26-11eb-9fd4-76aae9121d72.png)
</td>
</tr>
</table>

Required files-

[nav-mobile.zip](https://github.com/codeforcauseorg/codeforcause.org/files/6526369/nav-mobile.zip)

**Comment by mayankchaudhary19** [comment]
I would like to work on this issue

**Comment by KeenWarrior** [comment]
Please go ahead. 👍

**Comment by mayankchaudhary19** [comment]
I have redesigned the drawer for mobile view:

<img src="https://user-images.githubusercontent.com/43718753/119251755-d3206880-bbc5-11eb-9671-deb0474fd2da.jpeg" width="200" height="400" />

Web view:

https://user-images.githubusercontent.com/43718753/119252006-44145000-bbc7-11eb-9a46-461bc584304d.mp4


Also, changed the login button as shown above [down(sm)]. Please have a look and give suggestions for the same.

**Comment by KeenWarrior** [comment]
Raise the pull request.

**Comment by mayankchaudhary19** [comment]
Raised the pull request, please check #273

**Comment by mayankchaudhary19** [comment]
@KeenWarrior  @GangaChatrvedi please review the PR #273
