### ISSUE TITLE
Add Testimonials section on home page

### ISSUE THREAD

**Issue by KeenWarrior** [codeforcauseorg/codeforcause.org#28]
Add this section in between WhatWeStandFor and Team section

you can take ref from https://github.com/codeforcauseorg/codeforcause.org/blob/development/design/home_view/home_web.pdf

Expected result 

<img width="1416" alt="Screenshot 2020-07-05 at 6 15 04 PM" src="https://user-images.githubusercontent.com/25343183/86533012-bb77bd00-beeb-11ea-9a3d-cb6f2d9656de.png">

**Comment by sailikhithk** [comment]
I can start working on this...

**Comment by KeenWarrior** [comment]
@sailikhithk please go ahead

**Comment by GangaChatrvedi** [comment]
@sailikhithk Are you still working on it?

**Comment by sailikhithk** [comment]
Hi @GangaChatrvedi and @KeenWarrior, apologies. couldn't go through it cuz of some other commitments. I would request you to assign it to someone else.

**Comment by sarthakkundra** [comment]
@KeenWarrior I would like to work on this.

**Comment by GangaChatrvedi** [comment]
Go for it @sarthakkundra

**Comment by sarthakkundra** [comment]
@GangaChatrvedi is there any Slack, Discord etc. channel for discussion?

**Comment by KeenWarrior** [comment]
Discord: https://discord.gg/sZfpv7W  

-  room cfc-website

**Comment by GangaChatrvedi** [comment]
[box.zip](https://github.com/codeforcauseorg/codeforcause.org/files/4936517/box.zip)
@sarthakkundra You can get idea about what should be done for the box part from this.

**Comment by Abhishek-kumar09** [comment]
@sarthakkundra , For your help:
Almost all the code on homepage is written in https://github.com/codeforcauseorg/codeforcause.org/tree/development/src/views/pages/HomeView

Hope it would help you in digging through the codebase.

**Comment by GangaChatrvedi** [comment]
Closed with #46
