### ISSUE TITLE
Add header to Home page corresponding to given figma design

### ISSUE THREAD

**Issue by KeenWarrior** [codeforcauseorg/codeforcause.org#3]
Currently, there exists a header on the home page but that doesn't align with the prototype design.

We need to shift to provide design.

<img width="1410" alt="Screenshot 2020-06-24 at 4 01 53 PM" src="https://user-images.githubusercontent.com/25343183/85540049-285d9e00-b634-11ea-9244-bbf4d339060a.png">

**Comment by Abhishek-kumar09** [comment]
I would be working on it.

**Comment by GangaChatrvedi** [comment]
Yes. Please proceed.

![logo](https://user-images.githubusercontent.com/55276189/85581365-260e3a80-b65a-11ea-8a0b-e0d21cfc0634.png)

**Comment by Abhishek-kumar09** [comment]
Can we remove unnecessary code from `main header component` which was earlier written.

**Comment by GangaChatrvedi** [comment]
Yes. That will be good.
