### ISSUE TITLE
SpeedOptimization 1: website load slower due to bigger image sizes

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#42]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48255244/87595560-5b172580-c70c-11ea-9a6d-6b696fdd50a1.gif)
ALthough having a good internet speed, our website loads slower. This is clear that this is caused due to bigger image sizes that we actually dont need, because we are afterall using smaller resolution image on site.

WorkAround:
The mentors section should use smaller resolution pictures.
And youtube/course videos should fetch images from the youtube api (much much faster, because youtube is cached in almost everyones computer)

**Comment by Abhishek-kumar09** [comment]
This could help: https://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api

**Comment by KeenWarrior** [comment]
We are planning to set up a nest js server and use API at https://developers.google.com/youtube/v3/docs/channels/list

and respond to the list to be displayed from youtube itself. 

The idea originated after your PR. So kudos to you 🥳

**Comment by Abhishek-kumar09** [comment]
@KeenWarrior 
> We are planning to set up a nest js server

wohaaa!! mai bhi nestjs sikh rha hu...maza aeyega.
> The idea originated after your PR. So kudos to you

Arre bhaiyaa, I know it was already in your mind. But thanks for praising.
