### ISSUE TITLE
Add link for pledge website

### ISSUE THREAD

**Issue by pandafy** [codeforcauseorg/codeforcause.org#58]
Adding a section in footer for important links might be a good way to go.
Pledge website: https://pledge.codeforcause.org/

**Comment by KeenWarrior** [comment]
@pandafy Would you like to take up on this one?

**Comment by pandafy** [comment]
Apologies for late reply @KeenWarrior. I will surely take this one, but if anyone else wants to work on this before me they can go ahead.

**Comment by UdattaChowdhury** [comment]
Hello sir, I am a beginner and would like to take up this issue. Could you guide me on how can I go ahead?
