### ISSUE TITLE
Option in top bar gets vanished

### ISSUE THREAD

**Issue by ankitwarbhe** [codeforcauseorg/codeforcause.org#68]
when clicking on the campus leader option rest of the option gets vanished making difficult for the user to check other pages.

**Comment by Abhishek-kumar09** [comment]
> when clicking on the campus leader option rest of the option gets vanished

https://codeforcause.org/campusLeaders
@GangaChatrvedi , Is it intententional.

**Comment by Abhishek-kumar09** [comment]
For Contributors help:
Header Files are here: https://github.com/codeforcauseorg/codeforcause.org/tree/development/src/layouts/MainLayout/TopBar

**Comment by GangaChatrvedi** [comment]
Yes @Abhishek-kumar09 . A lot of changes are already done which are not pushed to master branch yet. You can see those changes [here](https://sandbox.codeforcause.org/)

**Comment by Abhishek-kumar09** [comment]
Oh fab, It gone unnoticed by me damn.. Well the new design is more fantastic.

**Comment by ankitwarbhe** [comment]
That's amazing we can consider these issue to be fixed after the push.
