### ISSUE TITLE
The open source button is Inactive

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#74]
![image](https://user-images.githubusercontent.com/48255244/93357562-1455c100-f85e-11ea-9d0c-97d56aa3bea3.png)
The open source div is not serving any click events, Is it good idea that clicking on open source would redirect a user to our open source projects @codeforcauseorg.
What is your view?

**Comment by KeenWarrior** [comment]
We are about to replace that with login/signup very soon

**Comment by Abhishek-kumar09** [comment]
OK I see it now, https://sandbox.codeforcause.org/
Its great..
The issue should be closed now?

**Comment by Abhishek-kumar09** [comment]
Issue closed because unrelevant.
