### ISSUE TITLE
Latency In Profile avatar sync

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#75]
![example-gif](https://user-images.githubusercontent.com/48255244/93597019-f744fd80-f9d7-11ea-9f85-cba00d7eafdd.gif)
We can either do some backend stuff to cache the user into our system or if not possible we could place a circular progress bar until the state of the user is known(loggedIn/Not)

**Comment by KeenWarrior** [comment]
The problem arises when the user has logged/removed out from other devices and other inconsistencies like that. 

So it may happen that you show the user that they are in but then remove them and ask them to log in.

**Comment by Abhishek-kumar09** [comment]
> The problem arises when the user has logged/removed out from other devices and other inconsistencies like that.

I didn't felt the same when I raised this issue.

Actually What I felt is:
Fetching data from Firebase takes some time, Untill the user data is not fully fetched, It is required to load a circular progress.

How you can recreate this?
1. Go to https://codeforcause.org/
2. Login with Google
3. Once Logged In refresh the browser again.
4. You can see the effect.
