### ISSUE TITLE
Code Clean-up suggestions

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#76]
src/components/PostCard

- [x] Files that can be deleted

| File | Remove Description |
| :--- | :--- |
| src/layouts/DocsLayout[Dir] | No Use |
| src/components/PostCard[Dir] | No Use |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/AuthGuard.js | Firebase Handles it |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/DraftEditor.js | Not Used |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/FilesDropzone.js |  Not Used|
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/GenericMoreButton.js |  Not Used |
| https://github.com/codeforcauseorg/codeforcause.org/blob/7aa5011cae6189cc2738f1601689ceb04fae68a1/src/components/GoogleAnalytics.js | No Use |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/GuestGuard.js | Firebase/ No Guest Login Allowed Currently |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/GuestRoute.js | Firebase |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/Label.js | Not Used |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/OnlineIndicator.js | Not Used (Mostly used In chat Apps) |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/PostAdd.js | Post Adds/ Blog Adds |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/ProjectCard.js | Not Used |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/QuillEditor.js | No Editor is used/ May require after updates |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/SettingsNotification.js | Not Used |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/SplashScreen.js | May be used in updates/ Not used Currently |
| https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/StackAvatars.js | Not Used/ Fetched from Firebase |

All the Files are important based on their functionality but is not used in current codebase but future feature updates can include this. So we can Delete it from here but archive this somewhere else.

- [x] Not used but Important Components: **Should not be removed**
They are the part of Redux and Redux-Router-DOM and state management
src/reducers
src/services
src/store

- [x] package that can be removed:
QuillEditor

- [x] Codes that can be optimised: 
Topbar
Auth, etc

- [x] Contents that can be moved to src/data
https://github.com/codeforcauseorg/codeforcause.org/blob/d4ad2c5b5f8c95531be5f71867206cd633c36b03/src/views/pages/CLView/CLViewData.js
https://github.com/codeforcauseorg/codeforcause.org/blob/ffd4352664c9d55a6d6cf73bb733df724e148ec7/src/views/pages/HomeView/HomeViewData.js

And other optimazations that should be followed after these changes.

**Comment by Abhishek-kumar09** [comment]
@GangaChatrvedi @KeenWarrior please have a look, I will do changes over your approval.

**Comment by GangaChatrvedi** [comment]
We'll be including these 2 files soon : 

https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/components/AuthGuard.js

https://github.com/codeforcauseorg/codeforcause.org/blob/7aa5011cae6189cc2738f1601689ceb04fae68a1/src/components/GoogleAnalytics.js

You can process others to remove/ do corrections.
