### ISSUE TITLE
The course view is not collapsing on clicking collapse button

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#80]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48255244/93862358-90795a00-fcdf-11ea-929e-ff2d78ef5b52.gif)

**Comment by Abhishek-kumar09** [comment]
> Please, Suggest issues related to HTML, CSS, js, react.
I would like to work on them.

@Roshan13046 Do you want to take it?

**Comment by Abhishek-kumar09** [comment]
Here is the link: https://codeforcause.org/ds-algo-with-java

**Comment by Roshan13046** [comment]
> > Please, Suggest issues related to HTML, CSS, js, react.
> > I would like to work on them.
> 
> @Roshan13046 Do you want to take it?

Yes, I have started working on the above issue.

**Comment by Abhishek-kumar09** [comment]
Here is the required folder:
https://github.com/codeforcauseorg/codeforcause.org/tree/development/src/views/pages/Courses

**Comment by Abhishek-kumar09** [comment]
This is the required file I guess: https://github.com/codeforcauseorg/codeforcause.org/blob/development/src/views/pages/Courses/Schedule.js

**Comment by Abhishek-kumar09** [comment]
@Roshan13046 Are you working on it.

**Comment by madhhuurrii** [comment]
Hii @Abhishek-kumar09 ,if roshan isnt working in this issue , i would like to work on this

**Comment by Abhishek-kumar09** [comment]
Okay, lets wait for some more hours to get a reply from him although he is not looking active on this thread.
You can start working on if more eager.

**Comment by Abhishek-kumar09** [comment]
@madhhuurrii you can start working now.

**Comment by ArunTeltia** [comment]
@madhhuurrii are you working on this?

**Comment by madhhuurrii** [comment]
I tried, but couldn't complete this @ArunTeltia if you want to do it please go ahead

**Comment by Roshan13046** [comment]
> Hii @Abhishek-kumar09 ,if roshan isnt working in this issue , i would like to work on this

No, I am not working on this issue. If anybody wants to work on it.
Please go ahead.

**Comment by ArunTeltia** [comment]
#80 fixed via #121
please close this issue @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
Thanks
