### ISSUE TITLE
Dynamically change the remaining number of characters required.

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#81]
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/48255244/93865035-5ca03380-fce3-11ea-84e1-b6e04999a4a0.gif)
Dynamically change the number of remaining characters as user types in something.

**Comment by Abhishek-kumar09** [comment]
Steps to reproduce:
1. go to https://codeforcause.org/
2. Click on any course
3. click on apply
4. Fill the third step.

**Comment by vandana1499** [comment]
May I know the file name for reference?

**Comment by Abhishek-kumar09** [comment]
Here is the code reference: https://github.com/codeforcauseorg/codeforcause.org/blob/development/src/views/pages/ApplicationsView/ApplicationSteps.js#L471-L538

Please open a PR against development branch.

**Comment by Abhishek-kumar09** [comment]
@vandana1499  Should I assign it to you?

**Comment by aymenhamada** [comment]
HI, check my PR please.

**Comment by Abhishek-kumar09** [comment]
Fix is merged.
