### ISSUE TITLE
No validation in Application Forms

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#82]
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/48255244/93866181-f74d4200-fce4-11ea-8c98-32ee8bc41f10.gif)

There must be validators for forms like:
- Mobile numbers can only have digits
- Email should have proper format
- Url and handles should be validated
- Year should be single digit.
- and so on.

**Comment by Saif807380** [comment]
Can I work on this?

**Comment by KeenWarrior** [comment]
@Saif807380 Sure. You can ask here in case of any doubts

**Comment by Saif807380** [comment]
I had a few queries

1. Should contact number include country code?
2. Is there an upper limit to Year field?

**Comment by KeenWarrior** [comment]
If we can include the coutry code that will be nice. We can preselect the country with help of https://ipstack.com/ and then provide a selector to change it.

Convert year to dropdown select with value range 1 to 6

**Comment by Abhishek-kumar09** [comment]
@Saif807380 Here is the required file to start with
https://github.com/codeforcauseorg/codeforcause.org/blob/development/src/views/pages/CLView/ApplyNowModal.js

**Comment by Saif807380** [comment]
Thanks, @Abhishek-kumar09. I have made the changes and submitted a PR (#84). Please review.

**Comment by KeenWarrior** [comment]
Solved by @Saif807380  in #86
