### ISSUE TITLE
Route to 404 is broken

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#89]
Tapping to any random url is taking to blank page, instead the user should have routed to 404 page.

**Comment by shankhanil007** [comment]
I would like to work on this issue.

**Comment by Abhishek-kumar09** [comment]
Great! Let us know if you stuck somewhere.

**Comment by shankhanil007** [comment]
Is the 404 page already designed?

**Comment by Abhishek-kumar09** [comment]
Yes, it is here: https://github.com/codeforcauseorg/codeforcause.org/blob/3ea24533ab0b2eb2efc935e9c32c541705073f2b/src/views/pages/Error404View.js

**Comment by shankhanil007** [comment]
Got It! I have sent a PR. Kindly review it.
