### ISSUE TITLE
Remove all the errors from the development console of website

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/codeforcause.org#92]
---
You can remove some number errors from the console and create a PR in chunks like removing some at a time
---

We are having many errors total 20 - 21 currently with rendering or other components. Reduce to 0 error is our goal.
Steps to reproduce: 
- start the development server with `npm run start`
- open console
- watch error panel

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48255244/94170144-5067d200-fead-11ea-9553-5b34a8371265.gif)

**Comment by Harshit-Dandriyal** [comment]
I would like to work on this issue

**Comment by Abhishek-kumar09** [comment]
@Harshit-Dandriyal 
Its already taken by @aymenhamada, We will open some new issues or you could also submit some new ones if you found any problem.

**Comment by ujjwal404** [comment]
It is showing error during authentication. 

![Screenshot 2020-10-05 at 5 08 04 PM](https://user-images.githubusercontent.com/63122405/95075598-1361d200-072e-11eb-9ef8-01d0c15db9e1.png)
![Screenshot 2020-10-05 at 5 08 14 PM](https://user-images.githubusercontent.com/63122405/95075609-1957b300-072e-11eb-906f-65cc81c83ec4.png)

**Comment by Itsaadarsh** [comment]
Hello there @Abhishek-kumar09 , I just sent a **PR** for this issue kindly review it and let me know if anything is needed.

**Comment by PranxXxD** [comment]
Hi, I would like to work on this issue, can you suggest me the ways?

**Comment by Abhishek-kumar09** [comment]
@PranxXxD This issue is already taken by @Itsaadarsh, I can suggest you some other issues if you want.

**Comment by PranxXxD** [comment]
okay!

**Comment by Itsaadarsh** [comment]
Hey @Abhishek-kumar09 why is PR not yet merged? I there something needed from my end?

**Comment by Abhishek-kumar09** [comment]
Really sorry from our side, we got more busy these days and things got left.

**Comment by Anuragtech02** [comment]
Hey @Abhishek-kumar09 I'd like to work on this, could you please assign this to me ?

**Comment by Abhishek-kumar09** [comment]
@Anuragtech02 the work is in progress by @Itsaadarsh. I guess he is not active due to some other commitments, you can take on the issue-with the work done by him, if he is fine.
@Itsaadarsh ping

**Comment by Itsaadarsh** [comment]
Hey @Abhishek-kumar09 I'm really sorry I got caught up in some other project of mine, don't worry I'll resolve this issue by tonight and commit all the changes! Thanks!

**Comment by SumaiyaSafdar** [comment]
Hey @Abhishek-kumar09  I'm extremely to new to open source contribution. I'd love to contribute to the organization, I only know java language and web development. Can you help me with my first contribution.

**Comment by Abhishek-kumar09** [comment]
closed in #197
