### ISSUE TITLE
Scroll Reset Component is not functioning, when switching to different routes

### ISSUE THREAD

**Issue by covalentbond** [codeforcauseorg/codeforcause.org#95]
While switching to a different route
The scroll postion is expected to move to top ( window.scrollTo(0, 0) )
But it remains fixed and does not work the way it was expected in the function

**Comment by covalentbond** [comment]
The possible reason I could find out is that location.state is undefined, it should be either null but not undefined
![image](https://user-images.githubusercontent.com/53327173/94249905-24486180-ff3e-11ea-8648-b572f424ebd8.png)

**Comment by KeenWarrior** [comment]
You can also take a look at https://stackoverflow.com/a/39345165

**Comment by covalentbond** [comment]
Hi, so yes I already tried using useEffect and the clean up function, wrapping with withRouter
As below

```
import { useEffect } from "react";
import { withRouter } from "react-router-dom";

function ScrollReset({ history }) {
  useEffect(() => {
    const unlisten = history.listen(() => {
      window.scrollTo(0, 0);
    });
    return () => {
      unlisten();
    };
  }, [history]);

  return null;
}

export default withRouter(ScrollReset);
```
But it was also not working as it was expected.

Tested the existing ScrollReset Component of the directory and the above new component in another project of mine.
Both worked over there, but not functioning here
Was unable to find the actual reason behind this

**Comment by KeenWarrior** [comment]
This seems like a complication. Are you feeling comfortable working on it? Or need someone associated with you on it?

**Comment by covalentbond** [comment]
> This seems like a complication. Are you feeling comfortable working on it? Or need someone associated with you on it?

Yes, it would be better

**Comment by covalentbond** [comment]
If anyone else is interested, can take this issue. I am currently not able to debug it

**Comment by ArunTeltia** [comment]
I am working on this

**Comment by ArunTeltia** [comment]
@Abhishek-kumar09 Have you tried this?
https://www.npmjs.com/package/react-router-scroll-top

**Comment by Abhishek-kumar09** [comment]
Not yet.

**Comment by ArunTeltia** [comment]
OKay i am trying it then

**Comment by ArunTeltia** [comment]
So I tried a lot of things but nothing works, The problem with this is the page is in the form of overflow:scroll now when we are trying to make it to ScrollTop the page render this component but the problem here is The page is already on top (because of the TopBar) , We can resolve this issue but we need to make the overflow to be visible 
Now the problem with this we have to give margin-bottom on the topbar and the scrollbar will appear at the topbar as well 

I am not able to deduct any other solution to this, can you help me @Abhishek-kumar09
