### ISSUE TITLE
Text not readable

### ISSUE THREAD

**Issue by gautamkrishnar** [codeforcauseorg/codeforcause.org#96]
<img width="1429" alt="Screenshot 2020-09-25 at 1 03 50 PM" src="https://user-images.githubusercontent.com/8397274/94239760-e8a69b00-ff2f-11ea-8c52-1d8c2d5bc582.png">

**Comment by KeenWarrior** [comment]
@gautamkrishnar  Are you using some kind of plugin?

In https://sandbox.codeforcause.org, the original work seems to work perfectly

**Comment by gautamkrishnar** [comment]
@KeenWarrior just tried on my mobile too. The url you shared is showing like this on Chrome. I am not using any plugins:
![Screenshot_20200925-185553.jpg](https://user-images.githubusercontent.com/8397274/94272630-ea3c8700-ff60-11ea-9ac9-0f119ee1930a.jpg)

**Comment by gautamkrishnar** [comment]
@KeenWarrior, it is happening because the background color is set as `#EEF5FF` for the div but it is `#F2F6FF` in the wireframe. Font color is also different please check the PR: #97 :

<img width="1414" alt="Screenshot 2020-09-25 at 6 59 08 PM" src="https://user-images.githubusercontent.com/8397274/94273011-7f3f8000-ff61-11ea-9bf0-c6bf10dfdf06.png">

**Comment by gautamkrishnar** [comment]
@KeenWarrior looks like this is a browser-specific issue when enabling dark mode: https://github.com/codeforcauseorg/codeforcause.org/pull/97#issuecomment-699010871
